/**:
  ros__parameters:
    min_longitudinal_offset: 1.51
    max_longitudinal_offset: 1.71
    min_lateral_offset: -0.530
    max_lateral_offset: 0.530
    min_height_offset: 1.06
    max_height_offset: 1.34
