/**:
  ros__parameters:
    wheel_radius: 0.266 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.145 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 1.860 # between front wheel center and rear wheel center
    wheel_tread: 0.868 # between left wheel center and right wheel center
    front_overhang: 0.410 # between front wheel center and vehicle front
    rear_overhang: 0.740 # between rear wheel center and vehicle rear
    left_overhang: 0.105 # between left wheel center and vehicle left
    right_overhang: 0.105 # between right wheel center and vehicle right
    vehicle_height: 1.785
    max_steer_angle: 0.567 # [rad]
